### ISSUE TITLE
Overlay with arrow scrolls to the bottom of the page in Safari when activated

### ISSUE THREAD

**Issue by petrklus** [Financial-Times/o-overlay#104]
When the overlay with an arrow is triggered for the first time in Safari (tested IOS9 and desktop Safari 9.1), the view scrolls all the way down (the overlay is still displayed correctly). 

I've found mention of this in o-overlay source but the mitigation does not seem to be working.

See preview here:

http://cnkpreview.s3.amazonaws.com/ft1_origami/o-overlay/overlay-with-arrow.html

The only difference between plain demo and the above is addition of lipsum placeholder text.

**Comment by petrklus** [comment]
A quick mitigation seems to be removing the focus from the ```show``` function:

	// Give the overlay focus
	this.wrapper.setAttribute('tabindex', '0');
	this.wrapper.style.outline = 0;
	// this.wrapper.focus();

https://github.com/Financial-Times/o-overlay/blob/master/src/js/overlay.js#L254

**Comment by AlbertoElias** [comment]
@onishiweb I think this is related to the accessibility improvements you made, could you take a look?

**Comment by onishiweb** [comment]
@AlbertoElias yep I'll take a look in the morning, I think I know what's going on. Will test the theory and see if I can fix it without breaking the a11y updates.

**Comment by petrklus** [comment]
@onishiweb Thank you for looking into this! Any updates?

**Comment by onishiweb** [comment]
Hi @petrklus sorry it took a bit longer than expected to get sorted, I've opened a PR now (#105) that should fix the issue.
