### ISSUE TITLE
overlay alignment bug

### ISSUE THREAD

**Issue by pixelandpage** [Financial-Times/o-overlay#115]
When the button is narrow and right-aligned and the content of the overlay is wider than the button the overlay arrow isn’t lining up with the cta button properly. Also, if you click and dismiss the button a few times, the overlay gets narrower each time.

Example on JSbin: http://output.jsbin.com/cebamowoku

**Comment by alicebartlett** [comment]
Picking this up now. Hoping to fix for v1.X.X but i'm also working on a v2.X.X and if the fix for this involves a breaking change then it will go in there instead.

So, two bugs:

1. Overlay not lining up with the cta button properly
2. Click + Dismiss results in the overlay getting narrower each time.

**Comment by alicebartlett** [comment]
@pixelandpage Your JS bin has expired, does this accurately represent the bug you were having?
http://jsbin.com/gatipir/edit?html,css,output

**Comment by alicebartlett** [comment]
That JSBin has expired and I'm having trouble replicating this behaviour now, although I remember looking at it at the time and verifying it was a bug. >:(

**Comment by pixelandpage** [comment]
Hi - This can be replicated consistently by clicking the delete button on a myft list: https://www.ft.com/myft/lists. (You'll need to create a list on this page if you don't already have one.)

Updated JSBIN link: https://output.jsbin.com/tupesoxeri

**Comment by alicebartlett** [comment]
OK yep, this is a bug. Next major of this module will deprecate the arrow functionality (which has been moved to o-tooltip) so going to close this as the bug is not present in o-tooltip
