### ISSUE TITLE
Arrow not lining up with button and resizes on subsequent clicks.

### ISSUE THREAD

**Issue by leggsimon** [Financial-Times/o-overlay#141]
<img width="397" alt="screenshot 2017-04-27 15 05 44" src="https://cloud.githubusercontent.com/assets/11544418/25488546/38cbdbac-2b5f-11e7-9062-da73d5b0e026.png">
 
If you go to  the list view page under myFT https://www.ft.com/myft/list/your-list-uuid and press the "Delete" button, the overlay's arrow doesn't line up with the button on smaller screens but on subsequent clicks it gets closer and closer in it lines up but is too squashed.
![apr-27-2017 15-44-31](https://cloud.githubusercontent.com/assets/11544418/25489017/8434f10e-2b60-11e7-922c-d3b82929a991.gif)

**Comment by alicebartlett** [comment]
We shipped o-tooltip (https://github.com/Financial-Times/o-tooltip) and have deprecated this feature in o-overlay. o-tooltip has much better handling of edge cases like this, can you use that instead of o-overlay?

**Comment by alicebartlett** [comment]
Sure!
