### ISSUE TITLE
Remove deprecated camelcase `parentNode`and `noFocus` options

### ISSUE THREAD

**Issue by rowanbeentje** [Financial-Times/o-overlay#145]
https://github.com/Financial-Times/o-overlay/pull/144 spotted that the v2.0.0 release includes options that can only be set from javascript instantiations, not via the attribute-based creation.  To fix this, the `parentNode` and `noFocus` options were renamed to `parentnode` and `nofocus`, with a deprecation notice and automatic mapping if the old names are in use on projects.

In the next major version the `parentNode` and `noFocus` maps in `checkOptions()` should be removed with a `Migrating from...` entry in the release readme.

**Comment by notlee** [comment]
Also remove `visuallyHideTitle for the same reason: https://github.com/Financial-Times/o-overlay/pull/200
