### ISSUE TITLE
'fullscreen' option not preventing scroll

### ISSUE THREAD

**Issue by jonnywyatt** [Financial-Times/o-overlay#159]
The readme says the fullscreen option 'disables scroll on the underlying document'

This doesn't seem to work, the background doc does scroll?

As a side note, the description also says 'is dismissible with the back button' - do you mean the escape button instead?

**Comment by JakeChampion** [comment]
>The readme says the fullscreen option 'disables scroll on the underlying document'
>
>This doesn't seem to work, the background doc does scroll?
That sounds like a bug, is it reproducible on a demo page or did you notice this when implementing o-overlay into an application?

>As a side note, the description also says 'is dismissible with the back button' - do you mean the escape button instead?
We are using the History API to make the back button close the overlay.
https://github.com/Financial-Times/o-overlay/blob/1dafe6b69c779245d58fb750dd087cae412087f9/src/js/overlay.js#L135-L143

**Comment by notlee** [comment]
There's an explicit fullscreen option where the above is true. The fullscreen option forces the overlay to be fullscreen regardless of its content or the viewport size.

There is also implicit fullscreen functionality where the content of the model exceeds the height or width of the viewport. The implicit fullscreen does not prevent scroll. We can add that. 👍

**Comment by notlee** [comment]
Modal overlays now prevent document scroll also https://github.com/Financial-Times/o-overlay/releases/tag/v2.2.1
