### ISSUE TITLE
Custom class overriden by base styling

### ISSUE THREAD

**Issue by samuele-artuso** [Financial-Times/o-overlay#164]
I want to change the background color of an overlay and to do so I'm using the `class` option. However, my styling is getting overridden by the base styling, as shown in the screenshot below. This bug seems to be happening on and off and I haven't managed to reproduce it deterministically.

<details>
 <summary>Screenshot demostrating this bug</summary>

![image](https://user-images.githubusercontent.com/3853889/36422285-4e088b4a-1633-11e8-8d8f-0176191f9321.png)

</details>

**Comment by notlee** [comment]
Hey @samuele-artuso, after our chat on Slack I think I can close this issue as it is not a problem with o-overlay itself. But please let me know if there's any other way we can help. :)
