### ISSUE TITLE
fix visuallyHideTitle declaritively

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-overlay#199]
`data-o-overlay-heading-visuallyHideTitle` does not work as attributes are case insensitive and the options property becomes `opts.heading.visuallyhidetitle`. Therefore this conditional fails: https://github.com/Financial-Times/o-overlay/blob/f24469327a843da3efef49d27474b47e1887abfa/src/js/overlay.js#L277

<img width="596" alt="Screenshot 2019-08-28 at 15 34 19" src="https://user-images.githubusercontent.com/10405691/63865354-55580a80-c9a9-11e9-9543-fe371d368f8b.png">

**Comment by JakeChampion** [comment]
fixed via https://github.com/Financial-Times/o-overlay/pull/200
