### ISSUE TITLE
Remove any characters that aren't valid when generating a heading id.

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-overlay#224]
Remove any characters that aren't [a valid css identifier](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier) when generating the heading id.

It appears only whitespace is removed currently. 
https://github.com/Financial-Times/o-overlay/blob/81e779ae0af90616aeedb796ef42f3d9beb8855e/src/js/overlay.js#L246

Relates to https://github.com/Financial-Times/o-overlay/pull/223

**Comment by JakeChampion** [comment]
>[a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit
That in regex form is 👇 
```js
^(?!\d)(?!--)(?!-\d)([^\u{00000}-\u{00030}]|[a-zA-Z0-9-_])*
```
>identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".
I've yet to figure out how to encode this into a regex.

**Comment by chee** [comment]
> > [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit
> 
> That in regex form is point_down
> 
> ```js
> ^(?!\d)(?!--)(?!-\d)([^\u{00000}-\u{00030}]|[a-zA-Z0-9-_])+
> ```
> 
> > identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B&W?" or "B\26 W\3F".
> 
> I've yet to figure out how to encode this into a regex.

we could implement an actual parser here, which would be great fun, i'd use a state machine.

however, it may be more prudent to be more strict than the CSS spec and then people can open an issue if they run into an issue where they need something more.

How about this:

```js
 const headingId = this.opts.heading.title.toLowerCase()
  .replace(/[a-z0-9-]/g, '-')
  .replace(/[\s-]+/g, '-')
```
