### ISSUE TITLE
Close modal overlay when clicking the modal background

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#27]
Major sites has this feature, the modal overlay closes when you click on the modal background.
It is especially useful when you are on a touch device and don't want to try to touch that little close icon.

Isn't this something we should think about, if not default, but an optional feature?

**Comment by kaelig** [comment]
Thanks for pointing this, Roland (and sorry for the delay).

I agree we should add some options to be able to add these interactions:

- exit on "esc" key pressed
- exit on out-of-boundaries click

Can we add this in a v2.1? /cc @AlbertoElias @triblondon 

@roland-vachter would you be game for coding it?

**Comment by AlbertoElias** [comment]
We have talked about this before and decided not to go with it for consistency purposes. If the debate is on again, we should bring more people to the table

**Comment by kaelig** [comment]
I'm confused, after looking into it, it seems we already have these two things implemented: https://github.com/Financial-Times/o-overlay/blob/master/src/js/overlay.js#L215

**Comment by roland-vachter** [comment]
I didn't find how to activate it..

**Comment by AlbertoElias** [comment]
You can close on external click on non-modal overlays

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by Vallach** [comment]
What is the status of this issue, is it a "no-fix"?
Currently, clicking outside of the overlay will not close it.

**Comment by AlbertoElias** [comment]
This is not really a bug as this is how the module was designed. I'm going to close it for now as there hasn't really been much debate about this. If it comes up in the future, we can reopen
