### ISSUE TITLE
Overlay not positioned in the center

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#31]
Between certain window sizes, the overlay enters full height mode, but there would be enough place to position it to center horizontally. Probably there's a mismatch between the ranges of the vertical and horizontal positioning.

![image](https://cloud.githubusercontent.com/assets/4048999/5409903/a1e9cc84-81f7-11e4-9fbf-37741e745bf9.png)

**Comment by AlbertoElias** [comment]
nudging @roland-vachter

**Comment by roland-vachter** [comment]
So the overlay is positioned differently on the same window size, let's say 1024x768:
1. open the page with this window size
2. open the page with a higher window size, let's say full HD, and narrow it down to 1024x768.

The result of 1 and 2 are different in terms of positioning the overlay.

**Comment by AlbertoElias** [comment]
Fixed in #46
