### ISSUE TITLE
IE8 alignment issue

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#34]
![image](https://cloud.githubusercontent.com/assets/4048999/5630191/1e7f699a-95c4-11e4-9f17-ee2d637193a7.png)

**Comment by roland-vachter** [comment]
IE8 is a primary browser for FT.com, and all functionality that is included should fully support IE8.

**Comment by AlbertoElias** [comment]
Did you manage to load the overlay using the polyfill service?

**Comment by roland-vachter** [comment]
Yes, the latest polyfill service is on the page.

**Comment by roland-vachter** [comment]
The modal background isn't displayed either.

**Comment by AlbertoElias** [comment]
I can't seem to emulate this? I saw the modal background issue, but not the alignment one. Can you send me a test case please?

**Comment by roland-vachter** [comment]
Visit this page in IE8, logged in with a prod account: http://uat.ftalphaville.ft.com/marketslive/2014-10-22-2/
Click the commenting settings link.

This is how the overlay is created:

```javascript
var overlay = new Overlay(idOfTheOverlay, {
   html: form.getDomElement(),
   heading: {
      title: "Commenting Settings"
   },
   modal: true
});
overlay.open();
```

**Comment by AlbertoElias** [comment]
This is what I get in ie8 ![screen shot 2015-01-07 at 16 05 18](https://cloud.githubusercontent.com/assets/913117/5648623/c469acf8-9687-11e4-8ef1-0fae1e48bd5c.png)

In Chrome I get a chat but can't find the commenting settings link

**Comment by roland-vachter** [comment]
Then try TEST environment of FT.com, log in with a TEST account, and access any article. You should need to have a pseudonym set, if not, just put a comment and you'll be asked (that is using o-overlay as well :) )

**Comment by roland-vachter** [comment]
It seems this is coming from the content of the overlay, not the overlay itself.

**Comment by AlbertoElias** [comment]
I've fixed the modal background, I will push a pr to that soon with a refactor of the sass to deprecate placeholder classes
