### ISSUE TITLE
Overlay is not displayed in IE8 even if the polyfill was included

### ISSUE THREAD

**Issue by cristinanegoescu** [Financial-Times/o-overlay#35]
There is still an issue for the 'o-overlay' component in IE8. Even if I included the polyfill service, the overlay is not opened. I also tried the demo http://build.origami.ft.com/files/o-overlay@1.1.3/demos/overlay-with-arrow.html replacing the polyfill url using Charles application and the problem can be reproduced. Do you have any clue how this can be fixed?

**Comment by AlbertoElias** [comment]
What did you substitute the polyfill url with?

**Comment by AlbertoElias** [comment]
There's a pr open in the [polyfill service](https://github.com/Financial-Times/polyfill-service/pull/237) to support HTMLElement in ie8. The other issue is that registry demos use MutationObserver which in ie8 makes it break the whole page. That doesn't mean the module itself doesn't work but demos won't work

Adding the polyfill and removing the registry script, I managed to get the overlay to appear, but we still have the issue raised in #34

**Comment by triblondon** [comment]
Mutation observer dependency can be removed from the registry trivially, I posted instructions on how to do that while I was on holiday but if no-one's picked it up I can easily do it this afternoon.

We can also add a polyfill for it to the polyfill service (there's one in the web components project maintained by Google)=

**Comment by AlbertoElias** [comment]
@triblondon I didn't see that. Whatever solution we decide to go with, I think it would be useful for people to test demos in ie8 if we need to support it in some cases.

**Comment by AlbertoElias** [comment]
Can this be closed @cristinanegoescu?

**Comment by cristinanegoescu** [comment]
There are still issues in IE8. I would like to keep this issue open until the component will work in IE8. Thanks

**Comment by AlbertoElias** [comment]
But those issues are raised separately so the discussion for those is happening on separate thread, I was just suggesting it to simplify things as the issues you mentioned have been fixed

**Comment by cristinanegoescu** [comment]
IE8 issue: https://github.com/Financial-Times/o-overlay/issues/43
