### ISSUE TITLE
o-overlay__content bottom truncated in Firefox if it scrolls

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#38]
To reproduce access this: http://jsbin.com/temahokuto/1/edit?html,output
Make the area scrollable vertically. Note that it scrolls only to number 20, number 21 is not visible.

In comments this means that the save and cancel buttons are truncated and not visible.

**Comment by kaelig** [comment]
@AlbertoElias can you please look into this (an easy fix, I believe) and fix it in the rewrite you're currently doing?

**Comment by AlbertoElias** [comment]
@kaelig I was aware of it yes, and I think it happens in all browsers actually, I believe I saw it yesterday in Chrome. A commit must have broken it

**Comment by AlbertoElias** [comment]
Should be fixed in #42
