### ISSUE TITLE
Use an existing overlay/modal box script?

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-overlay#39]
After looking at all the issues opened recently (although some have been implementation issues, not from the module itself), the question arises: *is this module trying to re-invent the wheel, but with a square one*?

This type of pattern has been solved in a responsive, cross browser, accessible fashion for many years.

Should we spend the appropriate amount of energy doing this thing right (and maybe release it as a separate library to benefit from a broader community input), or… should we rely on an existing one (and skin it according to our designs)?

**Comment by onishiweb** [comment]
I think we've gone ahead with this now and it is being used now too?

@AlbertoElias @alicebartlett worth keeping this open?

**Comment by AlbertoElias** [comment]
Nope
