### ISSUE TITLE
No vertical scrollbar after page resize

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#53]
If the overlay is open and the browser window is resized to a lower height, there is no vertical scrollbar available to access the content at the bottom of the overlay
Affects:
- all browsers

![image](https://cloud.githubusercontent.com/assets/4048999/6059844/f4cae5ba-ad3e-11e4-8ccc-083b96323ae9.png)

![image](https://cloud.githubusercontent.com/assets/4048999/6059846/faaa0d62-ad3e-11e4-84c4-1ec5e40ff47e.png)

**Comment by AlbertoElias** [comment]
It seems similar to #51 You need to resize twice for the scrollbars to appear.
