### ISSUE TITLE
Accessibility: restore initial focus when leaving the dialog

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-overlay#54]
See https://www.marcozehe.de/2015/02/05/advanced-aria-tip-2-accessible-modal-dialogs/:

> Of course, Escape isn’t the only way to close your dialog. You would also provide a button to accept changes and execute on whatever functionality you desire. In any case, after you close the dialog, you must!!!, you absolutely must!!! then set focus back to the element that opened the dialog, or any other useful element from which the user of your app will most likely continue working.

**Comment by kaelig** [comment]
Related to #45

**Comment by onishiweb** [comment]
I think this, #45 and #48 are all worth doing at the same time. I'll look into these in a block of work this week and get these bits fixed.
