### ISSUE TITLE
o-overlay title has no font family

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#56]
I think it should have some sensible default. Unfortunately there's no option (as far as I know) to specify a custom class to it and apply some styles.

Using it for comments we would like to have a default font family (not the very default of the page), but we can't just override styles of core overlay elements.

**Comment by AlbertoElias** [comment]
We decided not to force any font family on modules so you can set whatever you want. Can't you do

```scss
.o-overlay {
    font-family: BentonSans
}
```

while obviously loading BentonSans or your desired font from o-fonts or whatever font loading system you have in place.

**Comment by roland-vachter** [comment]
This is tricky, for sure. The point is that it affects all other module's overlay's. I'm not sure how could this be resolved. Maybe this could be a topic for the origami meeting.

**Comment by AlbertoElias** [comment]
This has been decided in previous Origami meetings. If you think your module needs to set a font, I can understand o-comments might be a special case, but we prefer to be font agnostic and leave it to products to decide. We're not setting any font at all, so it should be easy to override

**Comment by roland-vachter** [comment]
Hmm ok.

**Comment by roland-vachter** [comment]
Ok. I'll close it for now, we'll see how we can resolve it.
