### ISSUE TITLE
Alignment of arrow - compact overlay

### ISSUE THREAD

**Issue by manalishi79** [Financial-Times/o-overlay#57]
Arrow at the top of the overlay box allowed to be aligned. i.e. a certain distance from the corners rather than automatically centred.

![overlay](https://cloud.githubusercontent.com/assets/3977053/6166383/8f104a26-b2a7-11e4-8b09-73f5c0171170.png)

**Comment by kaelig** [comment]
Looks like a positioning issue that could be hacked in manually instead of being a parameter built into the module itself.

**Comment by AlbertoElias** [comment]
It can be hacked, but I think it should be built into the module even as a default behaviour. If the overlay doesn't fit centered because the trigger or the target is too far to the left or right, top or bottom, the arrow can move.

**Comment by expe** [comment]
Is this still a problem?

![screen shot 2015-11-03 at 10 57 42](https://cloud.githubusercontent.com/assets/4994123/10906434/585139ae-8219-11e5-8211-4e6cf994bbd0.png)

**Comment by AlbertoElias** [comment]
It was fixed for that specific implementation, o-overlay still doesn't support it

**Comment by alicebartlett** [comment]
I've added this behaviour to o-tooltip.
It might need some refinement but the next major of o-overlay will be removing the arrow stuff completely.
