### ISSUE TITLE
iPad tap on body doesn't close the overlay

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#58]
http://jsbin.com/xotawunuwa/1

**Comment by AlbertoElias** [comment]
I've managed to reproduce, your demo was missing the polyfill service. It seems this is due to:

http://www.quirksmode.org/blog/archives/2010/09/click_event_del.html

I don't know what the best approach to this might be. Maybe listening for touchstart as well.

**Comment by AlbertoElias** [comment]
Right, I tested out adding touchstart and it does work. Will release as soon as I fix the page scroll bug on Safari
