### ISSUE TITLE
Arrowed overlay demo not appearing

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-overlay#62]
The arrowed demo does not show up unless you expand the demo.  placing the button inside a container with a fixed height would hold the demo frame open to an appropriate height, wouldn't it?

**Comment by triblondon** [comment]
I'm referring here to 'overlay-with-arrow' on http://registry.origami.ft.com/components/o-overlay@1.4.0

**Comment by AlbertoElias** [comment]
Same as #18 But yes, that would be a solution
