### ISSUE TITLE
Destroy doesn't remove the object from the array of overlays

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#66]
Destroy should remove the object from the array of overlays, not just delete.

**Comment by roland-vachter** [comment]
Related to https://github.com/Financial-Times/o-overlay/issues/40

**Comment by AlbertoElias** [comment]
It is removed [here](https://github.com/Financial-Times/o-overlay/blob/master/src/js/overlay.js#L425) It's actually not an object, not an array. As this is not the issue, I'll close this

**Comment by roland-vachter** [comment]
Ah ok. But still, destroying and creating another one with the same ID has issues (cannot close with ESC in IE8). After destroying you can't create another overlay with the same ID?
