### ISSUE TITLE
Prevent pinch to zoom from closing overlay

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/o-overlay#69]

**Comment by alicebartlett** [comment]
Relevant for implementation: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures

**Comment by alicebartlett** [comment]
also tho http://caniuse.com/#feat=pointer

**Comment by rowanmanning** [comment]
I think we'll probably be rebuilding o-overlay before this particular issue gets done. Also nobody has bugged us about this in 5 years so probably not a priority
