### ISSUE TITLE
Overlay with arrow initialized the first time over the target button

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#71]
The Share overlay box from the bottom of the article opens over the Share button (when the page is not entirely scrolled down). It happens only at the first click on the button (each time the page is refreshed).

To reproduce visit FT.com INT environment: http://www.ft.com/intl/cms/s/2/4ea04522-47d6-11e4-a7d4-002128161462.html#slide0

**Comment by AlbertoElias** [comment]
Once #72 is merged, could you try with that version and see if it still happens?

**Comment by roland-vachter** [comment]
It seems that this issue was an ft-cms override issue, simply the paddings were not correctly overriden.
It seems to be not reproducible with the latest o-overlay untouched.

**Comment by AlbertoElias** [comment]
Can this be closed then @roland-vachter ?

**Comment by roland-vachter** [comment]
Yes.
