### ISSUE TITLE
`destroy` event doesn't bubble

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-overlay#77]
Because `this.context.removeChild(this.wrapper);` is called before `this.broadcast('destroy');`

The nicest way I can think to tackle it is to fire the event twice, once on `this.el` and once on `this.context`.

**Comment by AlbertoElias** [comment]
The change will be that it will be fired before the overlay is removed, I don't think the event should be fired in two places as it will bubble up and it's the overlay that gets destroyed, not the context

**Comment by gvonkoss** [comment]
Looks like this has been sorted https://github.com/Financial-Times/o-overlay/blob/35008f62b3fdfa6f436ffa719d4d7e8fec8601bd/src/js/overlay.js#L321-L335 — closing
