### ISSUE TITLE
Buttons at the bottom unavailable after scrolling inside the overlay

### ISSUE THREAD

**Issue by Vallach** [Financial-Times/o-overlay#78]
Steps:
1. Open an article page on FT.com in landscape mode
2. Scroll down to the comments widget
3. Open "Commenting Settings"
4. Tap "Autofollow" checkbox
5. Scroll up-down inside overlay

Result:
- "Save" & "Cancel" buttons are no longer displayed

Affects:
- iOS 8.2
- iPhone 5

![img_0072](https://cloud.githubusercontent.com/assets/3929840/6823171/66392174-d2ee-11e4-855e-14c8fc2c2433.PNG)
![img_0073](https://cloud.githubusercontent.com/assets/3929840/6823172/663bc488-d2ee-11e4-9023-ec5535f50b1d.PNG)

**Comment by AlbertoElias** [comment]
I've been testing in an iPhone 5C with iOS8. Seems to happen when the keyboard comes out or you get both safari bars. I managed to get that blank bit at the bottom of the overlay. But you can actually still scroll the upper bit and reach the buttons. Seems that it resizes properly when it gets smaller, but not always when it has to become larger again.
