### ISSUE TITLE
Shouldn't run viewport.listenTo('resize')

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/o-overlay#79]
This should be up to products, not being forced by the module. Would be a breaking change though

**Comment by alicebartlett** [comment]
Anyone remember what the origin of the change was? Did someone request it...?

**Comment by JakeChampion** [comment]
I don't remember :-(

**Comment by AlbertoElias** [comment]
I believe it was something about this setting a listener on the document,
which is outside of the scope of the component so it should be up to
products

**Comment by gvonkoss** [comment]
Closing as it is not currently relevant or requested.
