### ISSUE TITLE
Overlay arrow missing after resize to a screen width less than the width of the overlay

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#84]
Resizing the browser window horizontally to a small width will cause the overlay's arrow do disappear
Affects:
- All browsers

![image](https://cloud.githubusercontent.com/assets/4048999/7907851/433a3e90-0847-11e5-8e88-6b82e75f0405.png)

**Comment by AlbertoElias** [comment]
Might this be related to your override? If you scroll to the right, can you still not see the arrow?

**Comment by roland-vachter** [comment]
No. I found the reason, and I'm working on a fix.
It enters the full-width mode, which adds an overflow: hidden, which hides the :before and :after elements.
I will create a pull request in a couple of mintes.

**Comment by roland-vachter** [comment]
Closed means released? Because we are interested when this will be released, to be able to retest.

**Comment by AlbertoElias** [comment]
It gets closed automatically when you merge the pr. I'll make the release right away

**Comment by roland-vachter** [comment]
Ah ok, I see.
Release, that would be wonderful :)

**Comment by AlbertoElias** [comment]
Done
