### ISSUE TITLE
Jumping around on iPad

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#99]
If a modal overlay has a form with a select box, clicking the select box triggers a weird jumping of the overlay.
Probably an iOS issue, but best to keep track of known issues.

**Comment by chee** [comment]
Without a demo it's difficult to know if this has been fixed.

i've created this demo: https://output.jsbin.com/hehopiwide/1

<details>
<summary>the html</summary>
<pre><code>
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
  &lt;meta charset="utf-8"&gt;
  &lt;meta name="viewport" content="width=device-width"&gt;
  &lt;title&gt;JS Bin&lt;/title&gt;
  &lt;link rel="stylesheet" href="https://www.ft.com/__origami/service/build/v2/bundles/css?modules=o-overlay&amp;brand=internal"/&gt;
  &lt;script src="https://www.ft.com/__origami/service/build/v2/bundles/js?modules=o-overlay" defer&gt;&lt;/script&gt;
  &lt;/head&gt;
&lt;body&gt;
helo
 &lt;button class="o-overlay-trigger o-buttons o-buttons--secondary o-buttons--big" data-o-overlay-id="overlay" data-o-overlay-src="#overlay" 
 data-o-overlay-heading-title="We&amp;apos;re not having trouble updating" 
 data-o-overlay-heading-shaded="false" data-o-overlay-modal="true" 
 data-o-overlay-preventclosing="false" data-o-overlay-zindex="20" 
 aria-pressed="false" aria-haspopup="true"&gt;
 Launch overlay
  &lt;/button&gt;

&lt;script type="text/template" id="overlay"&gt;
	&lt;div class='demo-overlay'&gt;
		&lt;select&gt;
        &lt;option&gt;ffff&lt;/option&gt;
        &lt;option&gt;hoooo&lt;/option&gt;
        &lt;/select&gt;
	&lt;/div&gt;
&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;
</code></pre>
</details>
but i don't know if that is representative of the original issue from 2016. however it's an o-overlay with a select box.

i am going to test it on an ipad now, and report back.

**Comment by chee** [comment]
![web page with o-overlay and a closed select box](https://user-images.githubusercontent.com/178266/101148902-19810b80-3616-11eb-826a-1a33b15beee3.png)
![web page with o-overlay and an open select box](https://user-images.githubusercontent.com/178266/101148913-1e45bf80-3616-11eb-9334-322a4c20acc7.png)

**Comment by chee** [comment]
I did not experience any jumping about on iPad. If anyone experiences any jumping about on iPad. in the future please open a new issue.
